### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ZianTT** [vijos/malicious-code#6]
希望作者整一个能让g++编译时因为段错误crash的代码

**Comment by moesoha** [comment]
这听起来是编译器的 bug，应该升级编译器才对。

而且如果只是 segmentation fault 的话应该也不会对评测服务安全构成影响。

**Comment by ZianTT** [comment]
本来是在打某pku的比赛的，因为某题目来到了此仓库，感谢提供的灵感让我成功pass了此题（我因为对oi这方面了解的很少）再次感谢！
